import React, { useCallback, useEffect, useState } from 'react';
import { Alert, Button, Card, Divider, Flex, Heading, Link, LoadingSpinner, StatusTag, Text, hubspot } from '@hubspot/ui-extensions';
import { PLAN_COMPARISON, productPlanLabel, safeProductError, subscriptionLabel } from '../product-ui';

const API_BASE = 'https://dealguard-api.rokad.co/api/v1';
type Json = Record<string, any>;
type Billing = { tier: string; status: string; currentPeriodEnd: string | null; checkoutConfigured: boolean; portalConfigured: boolean; entitled: boolean };
type Access = { role: string; entitled: boolean };
type Dashboard = { totalDeals?: number; readyDeals?: number; atRiskDeals?: number; criticalDeals?: number; averageScore?: number; incompleteHandoffs?: number; lastScanAt?: string | null; nextScanAt?: string | null; topIssues?: Array<{ code: string; label: string; count: number }> };

type Analytics = { redacted?: boolean; current?: { totalDeals?: number; averageScore?: number; criticalEvents?: number; atRiskEvents?: number; readyEvents?: number; amountAtRisk?: number; pipelineAmount?: number; averageStageAgeDays?: number }; trend?: Array<{ date: string; averageScore: number; critical: number; amountAtRisk: number; assessedDeals: number }>; policyImpact?: Array<{ policyId: string | null; policyName: string; averageScore: number; critical: number; amountAtRisk: number }> };

hubspot.extend<'home'>(() => <DealGuardHome />);
const money = (value: number) => new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP', maximumFractionDigits: 0, notation: Math.abs(value) >= 1_000_000 ? 'compact' : 'standard' }).format(value);

const DealGuardHome = () => {
  const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [dashboard, setDashboard] = useState<Dashboard>({}); const [billing, setBilling] = useState<Billing | null>(null); const [access, setAccess] = useState<Access | null>(null); const [overview, setOverview] = useState<Json>({}); const [analytics, setAnalytics] = useState<Analytics | null>(null); const [checkoutUrl, setCheckoutUrl] = useState<string | null>(null); const [portalUrl, setPortalUrl] = useState<string | null>(null);
  const request = async (path: string, options?: { method?: 'GET' | 'POST'; body?: Record<string, unknown> }) => { const response = await hubspot.fetch(`${API_BASE}${path}`, { method: options?.method ?? 'GET', timeout: 20000, ...(options?.body ? { body: options.body } : {}) }); const data = await response.json(); if (!response.ok) throw new Error(safeProductError(data?.error?.message)); return data; };
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [dashboardData, billingData, accessData, overviewData, analyticsData] = await Promise.all([request('/dashboard'), request('/billing'), request('/enterprise/access'), request('/enterprise/overview'), request('/enterprise/analytics?days=90').catch(() => null)]); setDashboard(dashboardData); setBilling(billingData); setAccess(accessData); setOverview(overviewData); setAnalytics(analyticsData); } catch (caught) { setError(safeProductError(caught instanceof Error ? caught.message : null, 'DealGuard Home could not be loaded. Please try again.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const action = async (task: () => Promise<void>, success: string) => { setWorking(true); setError(null); setNotice(null); try { await task(); setNotice(success); } catch (caught) { setError(safeProductError(caught instanceof Error ? caught.message : null)); } finally { setWorking(false); } };
  if (loading) return <LoadingSpinner label="Loading DealGuard" />;
  if (!billing || !access) return <Alert title="DealGuard unavailable" variant="danger">{error ?? 'Your DealGuard workspace is temporarily unavailable. Please try again.'}</Alert>;

  const plan = productPlanLabel(billing.tier); const health = String(overview?.health?.status ?? 'healthy'); const healthy = health === 'healthy' || health === 'ok'; const readyPercent = dashboard.totalDeals ? Math.round(((dashboard.readyDeals ?? 0) / dashboard.totalDeals) * 100) : 0; const needsAttention = (dashboard.criticalDeals ?? 0) + (dashboard.atRiskDeals ?? 0) + (dashboard.incompleteHandoffs ?? 0); const role = access.role.replaceAll('_', ' ');
  const current = analytics?.current ?? {}; const trend = analytics?.trend ?? []; const firstTrend = trend[0]; const lastTrend = trend[trend.length - 1]; const scoreDelta = firstTrend && lastTrend ? lastTrend.averageScore - firstTrend.averageScore : 0; const riskDelta = firstTrend && lastTrend ? lastTrend.amountAtRisk - firstTrend.amountAtRisk : 0;
  const issueCount = (dashboard.topIssues ?? []).reduce((sum, issue) => sum + issue.count, 0); const dataQuality = dashboard.totalDeals ? Math.max(0, Math.round(100 - Math.min(100, issueCount / dashboard.totalDeals * 20))) : 100; const policyCompliance = dashboard.totalDeals ? Math.round((dashboard.readyDeals ?? 0) / dashboard.totalDeals * 100) : 100; const remediationOpen = (dashboard.criticalDeals ?? 0) + (dashboard.atRiskDeals ?? 0); const amountAtRisk = Number(current.amountAtRisk ?? 0); const pipelineAmount = Number(current.pipelineAmount ?? 0); const exposurePercent = pipelineAmount > 0 ? Math.round(amountAtRisk / pipelineAmount * 100) : 0;

  return <Flex direction="column" gap="large">
    {error && <Alert title="We couldn't complete that action" variant="danger">{error}</Alert>}{notice && <Alert title="Update complete" variant="success">{notice}</Alert>}
    <Flex direction="row" justify="between" align="center" gap="medium"><Flex direction="column" gap="extra-small"><Heading>Revenue readiness</Heading><Text>See what needs attention across your pipeline, then act on the highest-impact gaps.</Text></Flex><Flex direction="row" gap="small" align="center"><StatusTag variant={healthy ? 'success' : 'warning'}>{healthy ? 'Workspace healthy' : 'Needs attention'}</StatusTag><StatusTag variant={billing.tier === 'free' ? 'default' : 'success'}>{plan} plan</StatusTag></Flex></Flex>
    {needsAttention > 0 ? <Alert title={`${needsAttention} item${needsAttention === 1 ? '' : 's'} need attention`} variant={(dashboard.criticalDeals ?? 0) > 0 ? 'danger' : 'warning'}>{(dashboard.criticalDeals ?? 0) > 0 ? `${dashboard.criticalDeals} critical deal${dashboard.criticalDeals === 1 ? '' : 's'} should be reviewed first.` : 'Review at-risk deals and incomplete handoffs to improve pipeline readiness.'}</Alert> : <Alert title="Pipeline is in good shape" variant="success">No critical, at-risk or incomplete handoff items are currently reported.</Alert>}

    <Flex direction="row" gap="medium" wrap="wrap"><Card><Flex direction="column" gap="extra-small"><Text variant="microcopy">READINESS SCORE</Text><Heading>{dashboard.averageScore ?? 0}/100</Heading><Text>{dashboard.totalDeals ?? 0} deals assessed</Text></Flex></Card><Card><Flex direction="column" gap="extra-small"><Text variant="microcopy">READY PIPELINE</Text><Heading>{readyPercent}%</Heading><Text>{dashboard.readyDeals ?? 0} deals ready</Text></Flex></Card><Card><Flex direction="column" gap="extra-small"><Text variant="microcopy">AT RISK</Text><Heading>{dashboard.atRiskDeals ?? 0}</Heading><StatusTag variant={(dashboard.atRiskDeals ?? 0) > 0 ? 'warning' : 'success'}>{(dashboard.atRiskDeals ?? 0) > 0 ? 'Review' : 'Clear'}</StatusTag></Flex></Card><Card><Flex direction="column" gap="extra-small"><Text variant="microcopy">CRITICAL</Text><Heading>{dashboard.criticalDeals ?? 0}</Heading><StatusTag variant={(dashboard.criticalDeals ?? 0) > 0 ? 'danger' : 'success'}>{(dashboard.criticalDeals ?? 0) > 0 ? 'Action required' : 'Clear'}</StatusTag></Flex></Card><Card><Flex direction="column" gap="extra-small"><Text variant="microcopy">HANDOFFS</Text><Heading>{dashboard.incompleteHandoffs ?? 0}</Heading><StatusTag variant={(dashboard.incompleteHandoffs ?? 0) > 0 ? 'warning' : 'success'}>{(dashboard.incompleteHandoffs ?? 0) > 0 ? 'Pending' : 'Complete'}</StatusTag></Flex></Card></Flex>

    <Flex direction="column" gap="small"><Flex direction="row" justify="between" align="center"><Flex direction="column"><Heading>Pipeline intelligence</Heading><Text>A 90-day executive view of movement, quality, governance, remediation and commercial risk.</Text></Flex>{analytics?.redacted ? <StatusTag variant="default">Enterprise insight</StatusTag> : <StatusTag variant="success">Live</StatusTag>}</Flex>
      <Flex direction="row" gap="medium" wrap="wrap">
        <Card><Flex direction="column" gap="extra-small"><Flex direction="row" justify="between"><Text variant="microcopy">MOMENTUM</Text><StatusTag variant={scoreDelta > 0 ? 'success' : scoreDelta < 0 ? 'warning' : 'default'}>{scoreDelta > 0 ? 'Improving' : scoreDelta < 0 ? 'Slipping' : 'Stable'}</StatusTag></Flex><Heading>{scoreDelta > 0 ? '+' : ''}{scoreDelta} pts</Heading><Text>Readiness movement over 90 days</Text><Text variant="microcopy">Stage age: {Number(current.averageStageAgeDays ?? 0).toFixed(1)} days average</Text></Flex></Card>
        <Card><Flex direction="column" gap="extra-small"><Flex direction="row" justify="between"><Text variant="microcopy">DATA QUALITY</Text><StatusTag variant={dataQuality >= 90 ? 'success' : dataQuality >= 70 ? 'warning' : 'danger'}>{dataQuality >= 90 ? 'Strong' : dataQuality >= 70 ? 'Review' : 'Weak'}</StatusTag></Flex><Heading>{dataQuality}%</Heading><Text>Estimated field completeness</Text><Text variant="microcopy">{issueCount} readiness gaps detected across assessed deals</Text></Flex></Card>
        <Card><Flex direction="column" gap="extra-small"><Flex direction="row" justify="between"><Text variant="microcopy">POLICY COMPLIANCE</Text><StatusTag variant={policyCompliance >= 90 ? 'success' : policyCompliance >= 70 ? 'warning' : 'danger'}>{policyCompliance >= 90 ? 'On track' : 'Attention'}</StatusTag></Flex><Heading>{policyCompliance}%</Heading><Text>Deals meeting readiness policy</Text><Text variant="microcopy">{dashboard.readyDeals ?? 0} of {dashboard.totalDeals ?? 0} currently ready</Text></Flex></Card>
        <Card><Flex direction="column" gap="extra-small"><Flex direction="row" justify="between"><Text variant="microcopy">REMEDIATION</Text><StatusTag variant={remediationOpen === 0 ? 'success' : (dashboard.criticalDeals ?? 0) > 0 ? 'danger' : 'warning'}>{remediationOpen === 0 ? 'Clear' : 'Open work'}</StatusTag></Flex><Heading>{remediationOpen}</Heading><Text>Deals requiring remediation</Text><Text variant="microcopy">{dashboard.criticalDeals ?? 0} critical · {dashboard.atRiskDeals ?? 0} at risk</Text></Flex></Card>
        <Card><Flex direction="column" gap="extra-small"><Flex direction="row" justify="between"><Text variant="microcopy">COMMERCIAL EXPOSURE</Text><StatusTag variant={exposurePercent === 0 ? 'success' : exposurePercent < 20 ? 'warning' : 'danger'}>{exposurePercent === 0 ? 'Protected' : exposurePercent < 20 ? 'Watch' : 'Elevated'}</StatusTag></Flex><Heading>{analytics && !analytics.redacted ? money(amountAtRisk) : '—'}</Heading><Text>{analytics && !analytics.redacted ? `${exposurePercent}% of assessed pipeline at risk` : 'Available with Enterprise analytics'}</Text>{analytics && !analytics.redacted && <Text variant="microcopy">{riskDelta === 0 ? 'Exposure stable' : `${riskDelta > 0 ? 'Up' : 'Down'} ${money(Math.abs(riskDelta))} over the period`}</Text>}</Flex></Card>
      </Flex>
    </Flex>

    <Flex direction="row" gap="medium" wrap="wrap"><Card><Flex direction="column" gap="small"><Flex direction="row" justify="between" align="center"><Heading>Workspace</Heading><StatusTag variant={healthy ? 'success' : 'warning'}>{healthy ? 'Operational' : 'Review status'}</StatusTag></Flex><Text><Text format={{ fontWeight: 'bold' }}>Policy</Text> · {overview?.activePolicy?.name ?? 'Default readiness policy'}</Text><Text><Text format={{ fontWeight: 'bold' }}>Your access</Text> · {role}</Text><Divider /><Text variant="microcopy">Last assessment: {dashboard.lastScanAt ? new Date(dashboard.lastScanAt).toLocaleString() : 'Not completed yet'}</Text><Text variant="microcopy">Next assessment: {dashboard.nextScanAt ? new Date(dashboard.nextScanAt).toLocaleString() : 'Scheduled automatically'}</Text><Button variant="secondary" disabled={working} onClick={() => void load()}>Refresh data</Button></Flex></Card><Card><Flex direction="column" gap="small"><Flex direction="row" justify="between" align="center"><Heading>Plan & subscription</Heading><StatusTag variant={billing.status === 'active' ? 'success' : 'warning'}>{subscriptionLabel(billing.status)}</StatusTag></Flex><Text><Text format={{ fontWeight: 'bold' }}>{plan}</Text> plan</Text><Text>{billing.tier === 'free' ? 'Unlock native reporting, automation and daily monitoring with Growth.' : billing.tier === 'growth' || billing.tier === 'beta_growth' ? 'Your plan includes automation and native reporting. Enterprise adds organisation-wide governance.' : 'Enterprise governance is enabled for this workspace.'}</Text>{billing.currentPeriodEnd && <Text variant="microcopy">Current period ends {new Date(billing.currentPeriodEnd).toLocaleDateString()}.</Text>}<Flex direction="row" gap="small" wrap="wrap">{billing.tier !== 'enterprise' && <Button disabled={working || !billing.checkoutConfigured} onClick={() => void action(async () => { const result = await request('/billing/checkout', { method: 'POST', body: { tier: billing.tier === 'free' ? 'growth' : 'enterprise', interval: 'year', usageMode: 'capped', overageEnabled: false } }); setCheckoutUrl(result.url); }, 'Your secure plan checkout is ready.')}>{billing.tier === 'free' ? 'Upgrade to Growth' : 'Explore Enterprise'}</Button>}<Button variant="secondary" disabled={working || !billing.portalConfigured} onClick={() => void action(async () => { const result = await request('/billing/portal', { method: 'POST', body: {} }); setPortalUrl(result.url); }, 'Subscription management is ready.')}>Manage subscription</Button></Flex>{checkoutUrl && <Link href={{ url: checkoutUrl, external: true }}>Continue to secure checkout</Link>}{portalUrl && <Link href={{ url: portalUrl, external: true }}>Open subscription management</Link>}</Flex></Card></Flex>
    <Flex direction="column" gap="small"><Flex direction="row" justify="between" align="center"><Flex direction="column"><Heading>Priority readiness gaps</Heading><Text>Start with the issues affecting the most deals.</Text></Flex>{(dashboard.topIssues ?? []).length > 0 && <StatusTag variant="warning">Top {(dashboard.topIssues ?? []).slice(0, 5).length}</StatusTag>}</Flex>{(dashboard.topIssues ?? []).length > 0 ? (dashboard.topIssues ?? []).slice(0, 5).map((issue, index) => <Card key={issue.code}><Flex direction="row" justify="between" align="center" gap="medium"><Flex direction="column" gap="extra-small"><Text format={{ fontWeight: 'bold' }}>{index + 1}. {issue.label}</Text><Text variant="microcopy">Improving this rule can raise readiness across affected deals.</Text></Flex><StatusTag variant={index === 0 ? 'danger' : 'warning'}>{issue.count} affected</StatusTag></Flex></Card>) : <Card><Text>No recurring readiness gaps are currently reported.</Text></Card>}</Flex>
    <Flex direction="column" gap="small"><Flex direction="row" justify="between" align="center"><Flex direction="column"><Heading>Plans</Heading><Text>Compare capabilities when you need more automation or governance.</Text></Flex><StatusTag variant="default">Current: {plan}</StatusTag></Flex>{PLAN_COMPARISON.map((row) => <Card key={row.feature}><Flex direction="column" gap="extra-small"><Text format={{ fontWeight: 'bold' }}>{row.feature}</Text><Flex direction="row" gap="medium" wrap="wrap"><Text>Free · {row.free}</Text><Text>Growth · {row.growth}</Text><Text>Enterprise · {row.enterprise}</Text></Flex></Flex></Card>)}</Flex>
  </Flex>;
};
