import { AppError } from './errors.js';
import { activePolicy } from './governance.js';
import type { DealAssessment, Env, RequestIdentity } from './types.js';
import { requireEnterprisePermission } from './enterprise-access.js';

function number(value: unknown): number { return Number.isFinite(Number(value)) ? Number(value) : 0; }
function round(value: number, digits = 1): number { const scale = 10 ** digits; return Math.round(value * scale) / scale; }
function stageAgeDays(properties: Record<string, string | null | undefined>, stageId?: string): number | null { if (!stageId) return null; const value = properties[`hs_date_entered_${stageId}`]; if (!value) return null; const parsed = Date.parse(value); return Number.isFinite(parsed) ? Math.max(0, Math.floor((Date.now() - parsed) / 86400000)) : null; }

export async function recordAssessmentHistory(env: Env, portalId: string, assessment: DealAssessment, input: { trigger: string; properties?: Record<string, string | null | undefined>; policyId?: string | null }): Promise<void> {
 const props=input.properties??{}; const active=input.policyId===undefined?await activePolicy(env,portalId):null;
 await env.DB.prepare(`INSERT INTO assessment_history (id, portal_id, deal_id, score, grade, status, issue_codes_json, issue_count, pipeline_id, pipeline_label, stage_id, stage_label, owner_id, team_id, region_code, deal_type, deal_amount, stage_age_days, is_closed, is_won, policy_id, trigger_type, assessed_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).bind(crypto.randomUUID(),portalId,assessment.dealId,assessment.score,assessment.grade,assessment.status,JSON.stringify(assessment.issues.map(i=>i.code)),assessment.issues.length,assessment.pipelineId??props.pipeline??null,assessment.pipelineLabel,assessment.stageId??props.dealstage??null,assessment.stageLabel,assessment.ownerId??props.hubspot_owner_id??null,props.hs_team_id??props.dealguard_team_id??null,props.region??props.dealguard_region??null,props.dealtype??props.deal_type??null,assessment.dealAmount??(props.amount?Number(props.amount):null),stageAgeDays(props,assessment.stageId??props.dealstage??undefined),assessment.isClosed?1:0,assessment.isWon?1:0,input.policyId??active?.id??null,input.trigger.slice(0,40),assessment.assessedAt).run();
}

async function aggregate(env:Env,portalId:string,since:string,filters:Record<string,string>):Promise<Record<string,unknown>>{
 const where=['portal_id = ?','assessed_at >= ?',filters.pipelineId?'pipeline_id = ?':'',filters.stageId?'stage_id = ?':'',filters.ownerId?'owner_id = ?':'',filters.teamId?'team_id = ?':'',filters.regionCode?'region_code = ?':''].filter(Boolean).join(' AND '); const params:unknown[]=[portalId,since]; for(const key of ['pipelineId','stageId','ownerId','teamId','regionCode'])if(filters[key])params.push(filters[key]);
 const current=await env.DB.prepare(`SELECT COUNT(DISTINCT deal_id) AS total_deals, AVG(score) AS average_score, SUM(CASE WHEN status='critical' THEN 1 ELSE 0 END) AS critical_events, SUM(CASE WHEN status='at_risk' THEN 1 ELSE 0 END) AS at_risk_events, SUM(CASE WHEN status='ready' THEN 1 ELSE 0 END) AS ready_events, SUM(CASE WHEN status!='ready' THEN COALESCE(deal_amount,0) ELSE 0 END) AS amount_at_risk, SUM(COALESCE(deal_amount,0)) AS pipeline_amount, AVG(stage_age_days) AS average_stage_age FROM assessment_history WHERE ${where}`).bind(...params).first<Record<string,unknown>>();
 const trend=await env.DB.prepare(`SELECT substr(assessed_at,1,10) AS date, AVG(score) AS average_score, SUM(CASE WHEN status='critical' THEN 1 ELSE 0 END) AS critical, SUM(CASE WHEN status!='ready' THEN COALESCE(deal_amount,0) ELSE 0 END) AS amount_at_risk, COUNT(DISTINCT deal_id) AS assessed_deals FROM assessment_history WHERE ${where} GROUP BY substr(assessed_at,1,10) ORDER BY date ASC LIMIT 370`).bind(...params).all<Record<string,unknown>>();
 const breakdown=async(column:string,label:string)=>{const rows=await env.DB.prepare(`SELECT COALESCE(${column},'unassigned') AS id, COALESCE(${label},COALESCE(${column},'Unassigned')) AS label, COUNT(DISTINCT deal_id) AS total_deals, AVG(score) AS average_score, SUM(CASE WHEN status='critical' THEN 1 ELSE 0 END) AS critical, SUM(CASE WHEN status!='ready' THEN COALESCE(deal_amount,0) ELSE 0 END) AS amount_at_risk FROM assessment_history WHERE ${where} GROUP BY ${column},${label} ORDER BY amount_at_risk DESC LIMIT 250`).bind(...params).all<Record<string,unknown>>();return(rows.results??[]).map(r=>({id:String(r.id),label:String(r.label),totalDeals:number(r.total_deals),averageScore:Math.round(number(r.average_score)),critical:number(r.critical),amountAtRisk:number(r.amount_at_risk)}));};
 const ownerRows=await breakdown('owner_id','owner_id'),teamRows=await breakdown('team_id','team_id'); const baseline=number(current?.average_score); const benchmark=(rows:Array<Record<string,any>>)=>rows.filter(r=>r.id!=='unassigned'&&r.totalDeals>=2).map(r=>({...r,scoreDelta:Math.round(number(r.averageScore)-baseline),position:number(r.averageScore)>=baseline?'above':'below'})).sort((a,b)=>b.scoreDelta-a.scoreDelta);
 const latest=await env.DB.prepare(`SELECT DISTINCT ON (deal_id) deal_id,score,status,issue_count,deal_amount,stage_age_days,owner_id,team_id,stage_label,is_closed,is_won,assessed_at FROM assessment_history WHERE ${where} ORDER BY deal_id,assessed_at DESC LIMIT 10000`).bind(...params).all<Record<string,unknown>>();
 const predictive=(latest.results??[]).filter(r=>!Boolean(r.is_closed)).map(r=>{const score=number(r.score),age=number(r.stage_age_days),issues=number(r.issue_count),signal=Math.min(100,Math.max(0,Math.round((100-score)*.55+Math.min(30,age)*.8+Math.min(10,issues)*3)));return{dealId:String(r.deal_id),riskSignal:signal,band:signal>=70?'high':signal>=40?'medium':'low',score,issueCount:issues,stageAgeDays:age,amount:number(r.deal_amount),ownerId:r.owner_id?String(r.owner_id):null,stage:r.stage_label?String(r.stage_label):null};}).sort((a,b)=>b.riskSignal-a.riskSignal).slice(0,25);
 const outcomes=await env.DB.prepare(`SELECT score,issue_count,stage_age_days,is_won,deal_amount FROM assessment_history WHERE ${where} AND is_closed=1 ORDER BY assessed_at DESC LIMIT 10000`).bind(...params).all<Record<string,unknown>>(); const closed=outcomes.results??[],won=closed.filter(r=>Boolean(r.is_won)),lost=closed.filter(r=>!Boolean(r.is_won)),avg=(rows:Record<string,unknown>[],key:string)=>rows.length?round(rows.reduce((s,r)=>s+number(r[key]),0)/rows.length):0;
 const issueRows=await env.DB.prepare(`SELECT issue_codes_json FROM assessment_history WHERE ${where} ORDER BY assessed_at DESC LIMIT 10000`).bind(...params).all<{issue_codes_json:string}>(); const issues=new Map<string,number>();for(const row of issueRows.results??[])for(const code of JSON.parse(row.issue_codes_json) as string[])issues.set(code,(issues.get(code)??0)+1);
 const heatmap=await env.DB.prepare(`SELECT COALESCE(pipeline_label,'Unknown') AS pipeline,COALESCE(stage_label,'Unknown') AS stage,COUNT(DISTINCT deal_id) AS deals,AVG(stage_age_days) AS average_age,MAX(stage_age_days) AS maximum_age,SUM(CASE WHEN status='critical' THEN 1 ELSE 0 END) AS critical FROM assessment_history WHERE ${where} GROUP BY pipeline_label,stage_label ORDER BY pipeline,average_age DESC`).bind(...params).all<Record<string,unknown>>();
 const handoff=await env.DB.prepare(`SELECT COUNT(*) AS total,SUM(CASE WHEN status='confirmed' THEN 1 ELSE 0 END) AS confirmed,AVG(CASE WHEN confirmed_at IS NOT NULL THEN EXTRACT(EPOCH FROM (confirmed_at::timestamptz-created_at::timestamptz))/3600.0 END) AS average_hours FROM handoffs WHERE portal_id=? AND created_at>=?`).bind(portalId,since).first<Record<string,unknown>>();
 const policyImpact=await env.DB.prepare(`SELECT COALESCE(p.name,'Ungoverned') AS policy_name,h.policy_id,MIN(h.assessed_at) AS first_assessed_at,MAX(h.assessed_at) AS last_assessed_at,AVG(h.score) AS average_score,SUM(CASE WHEN h.status='critical' THEN 1 ELSE 0 END) AS critical,SUM(CASE WHEN h.status!='ready' THEN COALESCE(h.deal_amount,0) ELSE 0 END) AS amount_at_risk FROM assessment_history h LEFT JOIN policy_versions p ON p.id=h.policy_id WHERE h.portal_id=? AND h.assessed_at>=? GROUP BY h.policy_id,p.name ORDER BY first_assessed_at ASC`).bind(portalId,since).all<Record<string,unknown>>();
 return{current:{totalDeals:number(current?.total_deals),averageScore:Math.round(baseline),criticalEvents:number(current?.critical_events),atRiskEvents:number(current?.at_risk_events),readyEvents:number(current?.ready_events),amountAtRisk:number(current?.amount_at_risk),pipelineAmount:number(current?.pipeline_amount),averageStageAgeDays:round(number(current?.average_stage_age))},trend:(trend.results??[]).map(r=>({date:String(r.date),averageScore:Math.round(number(r.average_score)),critical:number(r.critical),amountAtRisk:number(r.amount_at_risk),assessedDeals:number(r.assessed_deals)})),byPipeline:await breakdown('pipeline_id','pipeline_label'),byStage:await breakdown('stage_id','stage_label'),byOwner:ownerRows,byTeam:teamRows,byRegion:await breakdown('region_code','region_code'),failurePatterns:[...issues.entries()].map(([code,count])=>({code,count})).sort((a,b)=>b.count-a.count).slice(0,50),stageAgingHeatmap:(heatmap.results??[]).map(r=>({pipeline:String(r.pipeline),stage:String(r.stage),deals:number(r.deals),averageAgeDays:round(number(r.average_age)),maximumAgeDays:number(r.maximum_age),critical:number(r.critical)})),handoffSla:{total:number(handoff?.total),confirmed:number(handoff?.confirmed),completionRate:number(handoff?.total)?round(number(handoff?.confirmed)/number(handoff?.total)*100):0,averageHours:round(number(handoff?.average_hours))},policyImpact:(policyImpact.results??[]).map(r=>({policyId:r.policy_id?String(r.policy_id):null,policyName:String(r.policy_name),firstAssessedAt:r.first_assessed_at,lastAssessedAt:r.last_assessed_at,averageScore:Math.round(number(r.average_score)),critical:number(r.critical),amountAtRisk:number(r.amount_at_risk)})),benchmarking:{workspaceAverageScore:Math.round(baseline),owners:benchmark(ownerRows),teams:benchmark(teamRows)},predictiveRisk:{methodology:'deterministic_signal',deals:predictive,highRiskDeals:predictive.filter(r=>r.band==='high').length},outcomeCorrelation:{sampleSize:closed.length,won:won.length,lost:lost.length,winRate:closed.length?round(won.length/closed.length*100):0,wonAverageScore:avg(won,'score'),lostAverageScore:avg(lost,'score'),scoreDelta:round(avg(won,'score')-avg(lost,'score')),wonAverageIssues:avg(won,'issue_count'),lostAverageIssues:avg(lost,'issue_count'),wonAverageStageAgeDays:avg(won,'stage_age_days'),lostAverageStageAgeDays:avg(lost,'stage_age_days'),confidence:closed.length>=100?'strong':closed.length>=30?'directional':'limited'}};
}

export async function enterpriseAnalyticsV2(env:Env,identity:RequestIdentity,url:URL):Promise<Record<string,unknown>>{const access=await requireEnterprisePermission(env,identity,'analytics.view');const days=Math.min(730,Math.max(1,Number(url.searchParams.get('days')??90)||90)),since=new Date(Date.now()-days*86400000).toISOString(),filters:Record<string,string>={};for(const key of ['pipelineId','stageId','ownerId','teamId','regionCode']){const v=url.searchParams.get(key);if(v)filters[key]=v.slice(0,128)}for(const[scopeKey,filterKey]of[['pipelineIds','pipelineId'],['teamIds','teamId'],['ownerIds','ownerId'],['regionCodes','regionCode']]as const){const allowed=access.scope[scopeKey];if(allowed.length&&filters[filterKey]&&!allowed.includes(filters[filterKey]!))throw new AppError(403,'analytics_scope_denied','The selected analytics filter is outside your assigned scope.');if(allowed.length===1&&!filters[filterKey])filters[filterKey]=allowed[0]!}return{audience:url.searchParams.get('audience')??'executive',days,filters,...await aggregate(env,identity.portalId,since,filters)}}
export async function listAnalyticsViews(env:Env,identity:RequestIdentity):Promise<Array<Record<string,unknown>>>{await requireEnterprisePermission(env,identity,'analytics.view');const rows=await env.DB.prepare(`SELECT * FROM analytics_saved_views WHERE portal_id=? AND (is_shared=1 OR created_by_user_id=? OR lower(COALESCE(created_by_email,''))=lower(COALESCE(?,''))) ORDER BY is_shared DESC,name`).bind(identity.portalId,identity.userId,identity.userEmail).all<Record<string,unknown>>();return(rows.results??[]).map(r=>({id:r.id,name:r.name,audience:r.audience,filters:JSON.parse(String(r.filters_json??'{}')),columns:JSON.parse(String(r.columns_json??'[]')),isShared:Boolean(r.is_shared),createdAt:r.created_at,updatedAt:r.updated_at}))}
export async function saveAnalyticsView(env:Env,identity:RequestIdentity,value:unknown,viewId:string|null=null):Promise<Record<string,unknown>>{await requireEnterprisePermission(env,identity,'analytics.view');const input=value&&typeof value==='object'?value as Record<string,unknown>:{},name=typeof input.name==='string'?input.name.trim().slice(0,120):'';if(!name)throw new AppError(400,'analytics_view_name_required','A saved-view name is required.');const audiences=['executive','revops','sales_manager','representative','custom'],audience=audiences.includes(String(input.audience))?String(input.audience):'custom',id=viewId??crypto.randomUUID(),now=new Date().toISOString();await env.DB.prepare(`INSERT INTO analytics_saved_views (id,portal_id,name,audience,filters_json,columns_json,created_by_user_id,created_by_email,is_shared,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,audience=excluded.audience,filters_json=excluded.filters_json,columns_json=excluded.columns_json,is_shared=excluded.is_shared,updated_at=excluded.updated_at`).bind(id,identity.portalId,name,audience,JSON.stringify(input.filters??{}),JSON.stringify(Array.isArray(input.columns)?input.columns.slice(0,100):[]),identity.userId,identity.userEmail,input.isShared===true?1:0,now,now).run();return{id,name,audience,filters:input.filters??{},columns:Array.isArray(input.columns)?input.columns.slice(0,100):[],isShared:input.isShared===true,updatedAt:now}}
export async function deleteAnalyticsView(env:Env,identity:RequestIdentity,viewId:string):Promise<void>{await requireEnterprisePermission(env,identity,'analytics.view');await env.DB.prepare(`DELETE FROM analytics_saved_views WHERE id=? AND portal_id=? AND (created_by_user_id=? OR lower(COALESCE(created_by_email,''))=lower(COALESCE(?,'')))`).bind(viewId,identity.portalId,identity.userId,identity.userEmail).run()}
function csv(value:unknown):string{const text=typeof value==='string'?value:JSON.stringify(value??'');return `"${text.replaceAll('"','""')}"`}
export async function exportAnalyticsCsv(env:Env,identity:RequestIdentity,url:URL):Promise<Response>{await requireEnterprisePermission(env,identity,'analytics.export');const data=await enterpriseAnalyticsV2(env,identity,url),rows=data.byPipeline as Array<Record<string,unknown>>,lines=['pipeline_id,pipeline,total_deals,average_score,critical,amount_at_risk'];for(const row of rows)lines.push([row.id,row.label,row.totalDeals,row.averageScore,row.critical,row.amountAtRisk].map(csv).join(','));return new Response(lines.join('\n'),{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="dealguard-enterprise-analytics-${identity.portalId}.csv"`,'cache-control':'no-store'}})}
