import type { Env } from './types.js';

function shell(title: string, body: string, env: Env): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>body{font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;max-width:840px;margin:0 auto;padding:48px 24px;color:#18222d;line-height:1.65}a{color:#0b63ce}header{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #e6ebf0;padding-bottom:20px;margin-bottom:36px}.brand{font-weight:800;letter-spacing:-.02em}.badge{font-size:12px;background:#eaf3ff;color:#064a9b;padding:4px 8px;border-radius:99px}h1{font-size:40px;line-height:1.15;letter-spacing:-.035em}h2{margin-top:36px}code{background:#f4f6f8;padding:2px 5px;border-radius:4px}.cta{display:inline-block;background:#0b63ce;color:white;text-decoration:none;padding:12px 18px;border-radius:8px;font-weight:700}.muted{color:#657382}footer{border-top:1px solid #e6ebf0;margin-top:48px;padding-top:20px;color:#657382;font-size:14px}</style></head><body><header><div class="brand">DealGuard by Rokad</div><span class="badge">HubSpot app</span></header>${body}<footer>Support: <a href="mailto:${env.SUPPORT_EMAIL}">${env.SUPPORT_EMAIL}</a> · © Rokad Retail Ventures Private Limited</footer></body></html>`;
}

export function landingPage(env: Env): string {
  return shell('DealGuard by Rokad', `<h1>Find risky deals before they damage your forecast or handoff.</h1><p>DealGuard continuously checks HubSpot deals for missing ownership, stale activity, overdue close dates, weak stakeholder associations, incomplete fields, and closed-won handoff gaps.</p><p><a class="cta" href="${env.APP_BASE_URL}/oauth/install">Connect DealGuard to HubSpot</a></p><h2>Production capabilities</h2><ul><li>Deal readiness score and risk classification</li><li>HubSpot deal-record app card</li><li>Configurable pipeline rules and custom required fields</li><li>Scheduled, manual, and event-triggered assessments</li><li>Native DealGuard properties for HubSpot lists, reports, and workflows on Growth</li><li>Reusable custom-workflow outputs</li><li>Closed-won handoff confirmation</li><li>Governed Slack alerts</li><li>Pipeline summaries and digest emails</li><li>Encrypted multitenant credentials</li></ul><p class="muted">DealGuard reads the CRM data required for assessment. On Growth, administrators may explicitly enable writes to seven fixed <code>dealguard_*</code> properties created by the app. DealGuard does not write to other deal fields.</p>`, env);
}

export function installSuccessPage(env: Env): string {
  return shell('DealGuard connected', `<h1>DealGuard is connected.</h1><p>The first pipeline scan has been queued. Open a deal record in HubSpot, add the <strong>DealGuard Readiness</strong> app card, and use the connected-app Settings page to configure readiness rules. Existing customers upgrading to v1.2 must reauthorize the app before enabling native property sync.</p><p><a class="cta" href="https://app.hubspot.com">Return to HubSpot</a></p>`, env);
}

export function slackSuccessPage(env: Env): string {
  return shell('Slack connected', `<h1>Slack is connected.</h1><p>DealGuard can now deliver configured readiness and handoff alerts to the selected Slack channel. Return to DealGuard settings in HubSpot to enable alert types and send a test message.</p><p><a class="cta" href="https://app.hubspot.com">Return to HubSpot</a></p>`, env);
}

export function docsPage(env: Env): string {
  return shell('DealGuard setup guide', `<h1>Setup guide</h1><h2>1. Connect or reauthorize the app</h2><p>Select the HubSpot account you administer. Existing installations upgrading to v1.2 must reauthorize because native reporting adds deal and deal-schema write scopes.</p><h2>2. Add the record card</h2><p>Open a deal, customize the middle column, add <strong>DealGuard Readiness</strong>, then save the view.</p><h2>3. Run the first scan</h2><p>Open Marketplace → Connected apps → DealGuard → Settings. Review the defaults and run a portal scan.</p><h2>4. Configure governance</h2><p>Set stale-activity and stage-age thresholds, exclusions, core requirements, and custom required properties.</p><h2>5. Enable native reporting (Growth)</h2><p>Provision the seven DealGuard properties, enable native sync, save settings, and backfill existing assessments. These fields can then be used in HubSpot lists, views, reports, and workflows.</p><h2>6. Connect Slack (Growth)</h2><p>Connect a Slack workspace and channel, enable desired alert types, save settings, and send a test notification.</p><h2>7. Add the workflow action (Growth)</h2><p>In a deal-based workflow, add <strong>Assess deal with DealGuard</strong>. The action returns reusable readiness outputs and can optionally notify Slack.</p><h2>8. Confirm handoffs</h2><p>Resolve critical issues and confirm closed-won handoffs from the app card.</p><h2>Data removal</h2><p>Use Delete DealGuard data in settings or email <a href="mailto:${env.SUPPORT_EMAIL}">${env.SUPPORT_EMAIL}</a>. Deletion removes Rokad-hosted data and credentials. Values and custom-property definitions already present in the customer's HubSpot account remain customer CRM data until the customer removes them.</p>`, env);
}

export function privacyPage(env: Env): string {
  return shell('DealGuard privacy notice', `<h1>Privacy notice</h1><p>DealGuard processes the minimum HubSpot CRM data needed to assess deal readiness: deal identifiers and selected properties, association counts, portal and user identifiers, derived readiness results, audit events, configuration, and optional Slack delivery metadata.</p><h2>HubSpot property writes</h2><p>For Growth customers who explicitly enable native sync, DealGuard creates and updates seven fixed, namespaced <code>dealguard_*</code> deal properties. It does not write to customer-owned, non-DealGuard fields. Native sync is disabled by default.</p><h2>Credential security</h2><p>HubSpot OAuth tokens, Slack incoming-webhook URLs, and Slack access tokens are encrypted with AES-256-GCM before storage. Application secrets remain in the deployment platform's secret manager.</p><h2>Data use</h2><p>Data is used only to deliver DealGuard, maintain security, provide support, and improve reliability. Rokad does not sell customer CRM data.</p><h2>Retention and deletion</h2><p>Operational history is retained according to the subscribed plan. Customers can delete Rokad-hosted DealGuard data from app settings or contact <a href="mailto:${env.SUPPORT_EMAIL}">${env.SUPPORT_EMAIL}</a>. DealGuard-derived values already written into HubSpot and the associated property definitions remain in the customer's CRM unless the customer removes them.</p><p class="muted">Review this operational notice with Rokad's final corporate privacy policy before public Marketplace submission.</p>`, env);
}

export function termsPage(env: Env): string {
  return shell('DealGuard terms', `<h1>Service terms</h1><p>DealGuard is provided by Rokad Retail Ventures Private Limited. Customers remain responsible for reviewing findings and making commercial, forecasting, and delivery decisions.</p><h2>Service limitations</h2><p>DealGuard provides deterministic operational checks. Scores, native property values, workflow outputs, and alerts are decision-support signals, not guarantees of revenue, forecast accuracy, contract enforceability, or successful delivery.</p><h2>Acceptable use</h2><p>Customers must use DealGuard lawfully, maintain authorised HubSpot and Slack access, and avoid bypassing plan or security controls.</p><h2>Support</h2><p>Contact <a href="mailto:${env.SUPPORT_EMAIL}">${env.SUPPORT_EMAIL}</a>.</p><p class="muted">Replace this beta version with counsel-reviewed commercial terms before paid public launch.</p>`, env);
}

export function supportPage(env: Env): string {
  return shell('DealGuard support', `<h1>Support</h1><p>Email <a href="mailto:${env.SUPPORT_EMAIL}">${env.SUPPORT_EMAIL}</a> with the HubSpot portal ID, affected deal ID, approximate issue time, and any DealGuard request ID shown.</p><h2>Target response times</h2><ul><li>Security or widespread outage: 4 business hours</li><li>Blocking product issue: 1 business day</li><li>General question or enhancement: 2 business days</li></ul><h2>Status</h2><p>During beta, status notices are sent directly to registered administrators.</p>`, env);
}
