import type { Env } from './types.js';

function shell(title: string, body: string, env: Env): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>body{font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;max-width:840px;margin:0 auto;padding:48px 24px;color:#18222d;line-height:1.65}a{color:#0b63ce}header{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #e6ebf0;padding-bottom:20px;margin-bottom:36px}.brand{font-weight:800;letter-spacing:-.02em}.badge{font-size:12px;background:#eaf3ff;color:#064a9b;padding:4px 8px;border-radius:99px}h1{font-size:40px;line-height:1.15;letter-spacing:-.035em}h2{margin-top:36px}code{background:#f4f6f8;padding:2px 5px;border-radius:4px}.cta{display:inline-block;background:#0b63ce;color:white;text-decoration:none;padding:12px 18px;border-radius:8px;font-weight:700}.muted{color:#657382}footer{border-top:1px solid #e6ebf0;margin-top:48px;padding-top:20px;color:#657382;font-size:14px}</style></head><body><header><div class="brand">DealGuard by Rokad</div><span class="badge">HubSpot app</span></header>${body}<footer>Support: <a href="mailto:${env.SUPPORT_EMAIL}">${env.SUPPORT_EMAIL}</a> · © Rokad Retail Ventures Private Limited</footer></body></html>`;
}

export function landingPage(env: Env): string {
  return shell('DealGuard by Rokad', `<h1>Find risky deals before they damage your forecast or handoff.</h1><p>DealGuard continuously checks HubSpot deals for missing ownership, stale activity, overdue close dates, weak stakeholder associations, incomplete fields, and closed-won handoff gaps.</p><p><a class="cta" href="${env.APP_BASE_URL}/oauth/install">Connect DealGuard to HubSpot</a></p><h2>Production v1 capabilities</h2><ul><li>Deal readiness score and risk classification</li><li>HubSpot deal-record app card</li><li>Configurable pipeline rules and custom required fields</li><li>Scheduled and manual portal scans</li><li>Closed-won handoff confirmation</li><li>Pipeline health summaries and digest emails</li><li>Encrypted multitenant OAuth credential storage</li></ul><p class="muted">DealGuard requests read-only CRM access. It does not modify HubSpot records in v1.</p>`, env);
}

export function installSuccessPage(env: Env): string {
  return shell('DealGuard connected', `<h1>DealGuard is connected.</h1><p>The first pipeline scan has been queued. Open a deal record in HubSpot, add the <strong>DealGuard Readiness</strong> app card to the middle column, and use the connected-app Settings page to configure readiness rules.</p><p><a class="cta" href="https://app.hubspot.com">Return to HubSpot</a></p>`, env);
}

export function docsPage(env: Env): string {
  return shell('DealGuard setup guide', `<h1>Setup guide</h1><h2>1. Connect the app</h2><p>Start the OAuth installation and select the HubSpot account you administer.</p><h2>2. Add the record card</h2><p>Open any deal, choose <strong>Customize</strong> in the middle column, add <strong>DealGuard Readiness</strong> from the App card library, then save the view.</p><h2>3. Run the first scan</h2><p>Open Marketplace → Connected apps → DealGuard → Settings. Review the default readiness rules and click <strong>Run portal scan</strong>.</p><h2>4. Configure governance</h2><p>Set stale-activity and stage-age thresholds, select required fields, and add up to the plan limit of custom required properties.</p><h2>5. Confirm handoffs</h2><p>For closed-won deals, resolve critical issues and confirm the sales-to-delivery handoff from the app card.</p><h2>Data removal</h2><p>Use the Delete DealGuard data action in app settings or email <a href="mailto:${env.SUPPORT_EMAIL}">${env.SUPPORT_EMAIL}</a>.</p>`, env);
}

export function privacyPage(env: Env): string {
  return shell('DealGuard privacy notice', `<h1>Privacy notice</h1><p>DealGuard processes the minimum HubSpot CRM data needed to assess deal readiness. This includes deal identifiers and selected deal properties, association counts, HubSpot portal and user identifiers, readiness results, audit events, and app configuration.</p><h2>Credential security</h2><p>HubSpot OAuth access and refresh tokens are encrypted with AES-256-GCM before storage. Application secrets are stored in the deployment platform's secret manager.</p><h2>Data use</h2><p>Data is used only to deliver DealGuard, maintain security, provide support, and improve reliability. Rokad does not sell customer CRM data.</p><h2>Retention and deletion</h2><p>Assessment history is retained according to the subscribed plan. Customers can request deletion from app settings or by contacting <a href="mailto:${env.SUPPORT_EMAIL}">${env.SUPPORT_EMAIL}</a>.</p><p class="muted">This operational notice should be reviewed with Rokad's final corporate privacy policy before public Marketplace submission.</p>`, env);
}

export function termsPage(env: Env): string {
  return shell('DealGuard terms', `<h1>Service terms</h1><p>DealGuard is provided by Rokad Retail Ventures Private Limited. Customers remain responsible for reviewing readiness findings and making commercial, forecasting, and delivery decisions.</p><h2>Service limitations</h2><p>DealGuard provides deterministic operational checks. Scores and alerts are decision-support signals, not guarantees of revenue, forecast accuracy, contract enforceability, or successful delivery.</p><h2>Acceptable use</h2><p>Customers must use DealGuard lawfully, maintain authorised HubSpot access, and avoid attempting to bypass plan or security controls.</p><h2>Support</h2><p>Contact <a href="mailto:${env.SUPPORT_EMAIL}">${env.SUPPORT_EMAIL}</a> for support or contractual terms.</p><p class="muted">Replace this testing version with counsel-reviewed commercial terms before paid public launch.</p>`, env);
}

export function supportPage(env: Env): string {
  return shell('DealGuard support', `<h1>Support</h1><p>Email <a href="mailto:${env.SUPPORT_EMAIL}">${env.SUPPORT_EMAIL}</a> with the HubSpot portal ID, affected deal ID, approximate time of the issue, and any DealGuard request ID shown.</p><h2>Target response times</h2><ul><li>Security or widespread outage: 4 business hours</li><li>Blocking product issue: 1 business day</li><li>General question or enhancement: 2 business days</li></ul><h2>Status</h2><p>During beta, status notices are sent directly to registered administrators.</p>`, env);
}
