import type { Env } from './types.js';

function shell(title: string, body: string, env: Env): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>body{font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;max-width:840px;margin:0 auto;padding:48px 24px;color:#18222d;line-height:1.65}a{color:#0b63ce}header{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #e6ebf0;padding-bottom:20px;margin-bottom:36px}.brand{font-weight:800;letter-spacing:-.02em}.badge{font-size:12px;background:#eaf3ff;color:#064a9b;padding:4px 8px;border-radius:99px}h1{font-size:40px;line-height:1.15;letter-spacing:-.035em}h2{margin-top:36px}code{background:#f4f6f8;padding:2px 5px;border-radius:4px}.cta{display:inline-block;background:#0b63ce;color:white;text-decoration:none;padding:12px 18px;border-radius:8px;font-weight:700}.muted{color:#657382}footer{border-top:1px solid #e6ebf0;margin-top:48px;padding-top:20px;color:#657382;font-size:14px}</style></head><body><header><div class="brand">DealGuard by Rokad</div><span class="badge">HubSpot app</span></header>${body}<footer>Support: <a href="mailto:${env.SUPPORT_EMAIL}">${env.SUPPORT_EMAIL}</a> · © Rokad Retail Ventures Private Limited</footer></body></html>`;
}

export function landingPage(env: Env): string {
  return shell('DealGuard by Rokad', `<h1>Enterprise revenue governance for HubSpot.</h1><p>DealGuard combines deterministic deal-readiness scoring, approved policy versions, remediation SLAs, native reporting, governed handoffs, routed notifications, and durable delivery operations.</p><p><a class="cta" href="${env.APP_BASE_URL}/oauth/install">Connect DealGuard to HubSpot</a></p><h2>Enterprise capabilities</h2><ul><li>Deal readiness and amount-at-risk analytics</li><li>Versioned policy approval, simulation, and rollback</li><li>Durable remediation cases and associated HubSpot tasks</li><li>Slack, Teams Workflow, email, and signed webhook delivery</li><li>Retry, dead-letter, replay, and per-portal service health</li><li>Native DealGuard properties and workflow outputs</li><li>Subscription Checkout and customer billing portal</li><li>Encrypted multitenant credentials and role-controlled administration</li></ul><p class="muted">DealGuard writes only its fixed <code>dealguard_*</code> deal properties and remediation tasks explicitly created by the app. It does not autonomously change deal stage, owner, amount, close date, or forecast category.</p>`, env);
}

export function installSuccessPage(env: Env): string {
  return shell('DealGuard connected', `<h1>DealGuard is connected.</h1><p>The first pipeline scan has been queued. Add the <strong>DealGuard Readiness</strong> card, open DealGuard App Home, and configure the required policy, reporting, remediation, and delivery controls. Existing installations must reauthorize before using native properties or remediation tasks.</p><p><a class="cta" href="https://app.hubspot.com">Return to HubSpot</a></p>`, env);
}

export function slackSuccessPage(env: Env): string {
  return shell('Slack connected', `<h1>Slack is connected.</h1><p>DealGuard can now deliver configured readiness and handoff alerts to the selected Slack channel. Return to DealGuard settings to enable alert types and send a test message.</p><p><a class="cta" href="https://app.hubspot.com">Return to HubSpot</a></p>`, env);
}

export function billingSuccessPage(env: Env): string {
  return shell('DealGuard subscription started', `<h1>Your subscription is being activated.</h1><p>Stripe completed checkout. DealGuard will apply the subscription when the signed billing event is processed. Return to HubSpot and refresh Enterprise Home to confirm the active tier.</p><p><a class="cta" href="https://app.hubspot.com">Return to HubSpot</a></p>`, env);
}

export function billingCanceledPage(env: Env): string {
  return shell('DealGuard checkout canceled', `<h1>No subscription change was made.</h1><p>Checkout was canceled before completion. Your existing DealGuard tier remains unchanged.</p><p><a class="cta" href="https://app.hubspot.com">Return to HubSpot</a></p>`, env);
}

export function docsPage(env: Env): string {
  return shell('DealGuard setup guide', `<h1>Setup guide</h1><h2>1. Connect or reauthorize</h2><p>Select the HubSpot account you administer. Remediation adds HubSpot task write access; native reporting uses constrained deal and deal-schema writes.</p><h2>2. Configure App Home and policies</h2><p>Enable enterprise governance, assign roles, capture the baseline policy, and use simulation plus independent approval for revisions.</p><h2>3. Enable native reporting</h2><p>Provision the fixed DealGuard properties, enable native sync, and run a controlled backfill.</p><h2>4. Configure remediation</h2><p>Critical assessment issues can create durable cases and associated HubSpot tasks. Managers can acknowledge, assign, start, resolve, waive, close, or reopen cases. Overdue cases are escalated automatically.</p><h2>5. Configure delivery</h2><p>Add Microsoft Teams Workflow, email, or signed webhook destinations. Route by event type, severity, and pipeline. Failed deliveries retry with exponential backoff and enter a replayable dead-letter queue.</p><h2>6. Billing</h2><p>Use Stripe-hosted subscription Checkout for Growth or Enterprise and the Stripe Customer Portal for upgrades, payment methods, cancellation, and invoices. Manual Enterprise contracts can be applied by Rokad operations.</p><h2>7. Validate operations</h2><p>Review service health, pending deliveries, dead letters, overdue remediations, scan status, workflow outputs, and audit history.</p><h2>Data removal</h2><p>Data deletion removes Rokad-hosted assessments, cases, destination credentials, subscriptions, and operational data. DealGuard property values and HubSpot tasks already stored in the customer's HubSpot account remain customer-controlled CRM data.</p>`, env);
}

export function privacyPage(env: Env): string {
  return shell('DealGuard privacy notice', `<h1>Privacy notice</h1><p>DealGuard processes the minimum HubSpot data needed for readiness governance, including deal identifiers and selected properties, association counts, amount, owner and pipeline context, derived results, policy state, remediation cases, audit events, configuration, billing references, and delivery metadata.</p><h2>HubSpot writes</h2><p>DealGuard writes only its fixed <code>dealguard_*</code> deal properties and remediation tasks explicitly created by administrators, workflows, or enterprise assessment automation. It does not alter core commercial deal fields.</p><h2>Delivery credentials</h2><p>HubSpot OAuth tokens, Slack credentials, Teams Workflow URLs, generic webhook endpoints, and signing secrets are encrypted with AES-256-GCM before storage.</p><h2>Billing</h2><p>Stripe processes payment details. DealGuard stores Stripe customer/subscription identifiers, tier, status, billing period, and grace dates; it does not store card data.</p><h2>Retention and deletion</h2><p>Retention follows the subscribed tier. Administrators can delete Rokad-hosted DealGuard data. Values, custom-property definitions, and tasks already present in HubSpot remain customer-controlled unless the customer removes them.</p><p class="muted">Replace this operational notice with Rokad's counsel-reviewed privacy policy and subprocessor disclosure before public release.</p>`, env);
}

export function termsPage(env: Env): string {
  return shell('DealGuard terms', `<h1>Service terms</h1><p>DealGuard is provided by Rokad Retail Ventures Private Limited. Customers remain responsible for commercial, forecasting, policy, remediation, and delivery decisions.</p><h2>Subscriptions</h2><p>Paid access may be purchased through Stripe-hosted subscription Checkout or supplied under a separately executed enterprise order. Subscription status controls feature entitlement, including applicable trial and payment-failure grace periods.</p><h2>Service limitations</h2><p>DealGuard provides deterministic operational checks, governance workflows, tasks, alerts, and recommendations. These are decision-support controls, not guarantees of revenue, forecast accuracy, contract enforceability, or successful delivery.</p><h2>Support</h2><p>Contact <a href="mailto:${env.SUPPORT_EMAIL}">${env.SUPPORT_EMAIL}</a>.</p><p class="muted">Replace this beta version with counsel-reviewed commercial terms before public launch.</p>`, env);
}

export function supportPage(env: Env): string {
  return shell('DealGuard support', `<h1>Support</h1><p>Email <a href="mailto:${env.SUPPORT_EMAIL}">${env.SUPPORT_EMAIL}</a> with the HubSpot portal ID, affected deal/case/delivery ID, approximate issue time, and any request ID shown.</p><h2>Target response times</h2><ul><li>Security or widespread outage: 4 business hours</li><li>Blocking Enterprise issue: 1 business day</li><li>General question or enhancement: 2 business days</li></ul><h2>Operational diagnostics</h2><p>Enterprise administrators can inspect per-portal service health, failed deliveries, dead letters, remediation SLAs, scan status, and audit events from DealGuard App Home.</p>`, env);
}
