import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Button, Card, Divider, Flex, Heading, Input, Link, LoadingSpinner, MultiSelect, NumberInput, Select, StatusTag, Text, Toggle, hubspot } from '@hubspot/ui-extensions';

const API_BASE = 'https://dealguard-api.rokad.co/api/v1';
type Severity = 'info' | 'warning' | 'critical';
type Plan = 'free' | 'growth' | 'beta_growth';
type CustomRule = { property: string; label: string; weight: number; severity: Severity; stageIds: string[] };
type Settings = { rules: { staleDays: number; maxStageAgeDays: number; requireOwner: boolean; requireAmount: boolean; requireCloseDate: boolean; requireNextStep: boolean; requireCompany: boolean; requireContact: boolean; excludedPipelineIds: string[]; excludedStageIds: string[]; customRequiredProperties: CustomRule[] }; digest: { enabled: boolean; frequency: 'daily' | 'weekly'; recipients: string[]; dayOfWeek: number; hourUtc: number }; notifications: { slack: { enabled: boolean; alertOnCritical: boolean; alertOnHandoffRequired: boolean; alertOnHandoffConfirmed: boolean; cooldownMinutes: number } }; nativeSync: { enabled: boolean; includeSummary: boolean } };
type ProblemDeal = { dealId: string; dealName: string; pipelineLabel: string; stageLabel: string; score: number; status: 'ready' | 'at_risk' | 'critical'; readinessSummary: string; assessedAt: string };
type Dashboard = { plan: Plan; totalDeals: number; readyDeals: number; atRiskDeals: number; criticalDeals: number; averageScore: number; incompleteHandoffs: number; lastScanAt: string | null; nextScanAt: string; topIssues: Array<{ code: string; label: string; count: number }>; problemDeals: ProblemDeal[]; latestScan: null | { id: string; trigger: 'manual' | 'scheduled' | 'install'; status: 'running' | 'completed' | 'failed'; startedAt: string; completedAt: string | null; scannedCount: number; errorMessage: string | null } };
type Metadata = { pipelines: Array<{ id: string; label: string; stages: Array<{ id: string; label: string }> }>; properties: Array<{ name: string; label: string; groupName: string; type: string; fieldType: string }> };
type SlackStatus = { connected: boolean; entitled: boolean; teamName?: string; teamId?: string; channelName?: string; channelId?: string; connectedAt?: string; status?: 'active' | 'revoked' | 'error' };
type NativeSyncStatus = { entitled: boolean; enabled: boolean; status: 'not_provisioned' | 'provisioning' | 'ready' | 'backfilling' | 'error'; propertyVersion: number; provisionedAt: string | null; lastBackfillAt: string | null; lastBackfillCount: number; lastError: string | null };
type SettingsResponse = { plan: Plan; settings: Settings };
type RequestOptions = { method?: 'GET' | 'PUT' | 'POST' | 'DELETE'; body?: Record<string, unknown> };
hubspot.extend<'settings'>(() => <DealGuardSettings />);
const delay = (milliseconds: number) => new Promise<void>((resolve) => setTimeout(resolve, milliseconds));
const statusVariant = (status: ProblemDeal['status']): 'success' | 'warning' | 'danger' => status === 'ready' ? 'success' : status === 'at_risk' ? 'warning' : 'danger';
const nativeStatusVariant = (status: NativeSyncStatus['status']): 'success' | 'warning' | 'danger' | 'default' => status === 'ready' ? 'success' : status === 'error' ? 'danger' : status === 'provisioning' || status === 'backfilling' ? 'warning' : 'default';
const planLabel = (plan: Plan) => plan === 'beta_growth' ? 'Beta Growth' : plan === 'growth' ? 'Growth' : 'Free';
const formatDate = (value: string | null | undefined) => value ? new Date(value).toLocaleString() : 'Not yet';

const DealGuardSettings = () => {
  const [settings, setSettings] = useState<Settings | null>(null); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [metadata, setMetadata] = useState<Metadata | null>(null); const [slack, setSlack] = useState<SlackStatus | null>(null); const [nativeSync, setNativeSync] = useState<NativeSyncStatus | null>(null); const [slackAuthorizeUrl, setSlackAuthorizeUrl] = useState<string | null>(null); const [plan, setPlan] = useState<Plan>('free'); const [recipients, setRecipients] = useState(''); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const fetchJson = async (path: string, options?: RequestOptions) => { const response = await hubspot.fetch(`${API_BASE}${path}`, { method: options?.method ?? 'GET', timeout: 15000, ...(options?.body ? { body: options.body } : {}) }); const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message ?? 'DealGuard request failed.'); return data; };
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [settingsData, dashboardData, metadataData, slackData, nativeData] = await Promise.all([fetchJson('/settings') as Promise<SettingsResponse>, fetchJson('/dashboard') as Promise<Dashboard>, fetchJson('/metadata') as Promise<Metadata>, fetchJson('/integrations/slack') as Promise<SlackStatus>, fetchJson('/native-sync') as Promise<NativeSyncStatus>]); setSettings(settingsData.settings); setPlan(settingsData.plan); setRecipients(settingsData.settings.digest.recipients.join(', ')); setDashboard(dashboardData); setMetadata(metadataData); setSlack(slackData); setNativeSync(nativeData); setSlackAuthorizeUrl(null); } catch (caught) { setError(caught instanceof Error ? caught.message : 'DealGuard settings could not be loaded.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const refreshDashboard = async () => { const next = await fetchJson('/dashboard') as Dashboard; setDashboard(next); return next; };
  const refreshNativeSync = async () => { const next = await fetchJson('/native-sync') as NativeSyncStatus; setNativeSync(next); return next; };
  const settingsPayload = (): Settings | null => settings ? { ...settings, digest: { ...settings.digest, recipients: recipients.split(',').map((item) => item.trim()).filter(Boolean) } } : null;
  const save = async () => { const payload = settingsPayload(); if (!payload) return; setWorking(true); setError(null); setNotice(null); try { const response = await fetchJson('/settings', { method: 'PUT', body: payload as unknown as Record<string, unknown> }) as SettingsResponse; setSettings(response.settings); setRecipients(response.settings.digest.recipients.join(', ')); await refreshNativeSync(); setNotice('Configuration saved. DealGuard is now using the updated governance policy.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Settings could not be saved.'); } finally { setWorking(false); } };
  const scan = async () => { setWorking(true); setError(null); setNotice(null); try { await fetchJson('/scans', { method: 'POST', body: {} }); setNotice('Pipeline assessment started.'); for (let attempt = 0; attempt < 6; attempt++) { await delay(2000); const next = await refreshDashboard(); if (next.latestScan?.status !== 'running') { setNotice(next.latestScan?.status === 'completed' ? `Assessment completed: ${next.latestScan.scannedCount} deals analysed.` : 'Assessment did not complete. Review the status below.'); break; } } } catch (caught) { setError(caught instanceof Error ? caught.message : 'Pipeline assessment could not be started.'); } finally { setWorking(false); } };
  const testDigest = async () => { setWorking(true); setError(null); try { await fetchJson('/digest/test', { method: 'POST', body: {} }); setNotice('Test digest sent.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Test digest failed.'); } finally { setWorking(false); } };
  const prepareSlackConnection = async () => { setWorking(true); setError(null); try { const response = await fetchJson('/integrations/slack/connect', { method: 'POST', body: {} }) as { authorizeUrl: string }; setSlackAuthorizeUrl(response.authorizeUrl); setNotice('Workspace authorisation is ready.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Workspace connection could not be started.'); } finally { setWorking(false); } };
  const testSlack = async () => { setWorking(true); setError(null); try { await fetchJson('/integrations/slack/test', { method: 'POST', body: {} }); setNotice('Test notification sent.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Test notification failed.'); } finally { setWorking(false); } };
  const disconnectSlack = async () => { setWorking(true); setError(null); try { await fetchJson('/integrations/slack', { method: 'DELETE' }); setNotice('Workspace disconnected.'); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Workspace could not be disconnected.'); } finally { setWorking(false); } };
  const provisionNative = async () => { setWorking(true); setError(null); try { const next = await fetchJson('/native-sync/provision', { method: 'POST', body: {} }) as NativeSyncStatus; setNativeSync(next); setNotice('Reporting fields are ready. Enable sync and save before backfilling.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Reporting fields could not be provisioned.'); } finally { setWorking(false); } };
  const backfillNative = async () => { const payload = settingsPayload(); if (!payload) return; setWorking(true); setError(null); try { const saved = await fetchJson('/settings', { method: 'PUT', body: payload as unknown as Record<string, unknown> }) as SettingsResponse; setSettings(saved.settings); await fetchJson('/native-sync/backfill', { method: 'POST', body: {} }); setNativeSync((current) => current ? { ...current, enabled: true, status: 'backfilling' } : current); setNotice('Historical reporting backfill started.'); for (let attempt = 0; attempt < 8; attempt++) { await delay(2000); const next = await refreshNativeSync(); if (next.status !== 'backfilling') { setNotice(next.status === 'ready' ? `Backfill completed for ${next.lastBackfillCount} deals.` : next.lastError ?? 'Backfill did not complete.'); break; } } } catch (caught) { setError(caught instanceof Error ? caught.message : 'Reporting backfill failed.'); } finally { setWorking(false); } };
  const propertyOptions = useMemo(() => (metadata?.properties ?? []).map((property) => ({ label: `${property.label} (${property.name})`, value: property.name })), [metadata]);
  const pipelineOptions = useMemo(() => (metadata?.pipelines ?? []).map((pipeline) => ({ label: pipeline.label, value: pipeline.id })), [metadata]);
  const stageOptions = useMemo(() => (metadata?.pipelines ?? []).flatMap((pipeline) => pipeline.stages.map((stage) => ({ label: `${pipeline.label} — ${stage.label}`, value: stage.id }))), [metadata]);
  if (loading) return <LoadingSpinner label="Loading DealGuard control centre" />;
  if (!settings || !dashboard || !metadata || !slack || !nativeSync) return <Alert title="DealGuard unavailable" variant="danger">{error ?? 'Configuration is unavailable.'}</Alert>;
  const maxCustomRules = plan === 'free' ? 3 : 25;
  const updateRule = <K extends keyof Settings['rules']>(key: K, value: Settings['rules'][K]) => setSettings({ ...settings, rules: { ...settings.rules, [key]: value } });
  const updateDigest = <K extends keyof Settings['digest']>(key: K, value: Settings['digest'][K]) => setSettings({ ...settings, digest: { ...settings.digest, [key]: value } });
  const updateSlack = <K extends keyof Settings['notifications']['slack']>(key: K, value: Settings['notifications']['slack'][K]) => setSettings({ ...settings, notifications: { ...settings.notifications, slack: { ...settings.notifications.slack, [key]: value } } });
  const updateNative = <K extends keyof Settings['nativeSync']>(key: K, value: Settings['nativeSync'][K]) => setSettings({ ...settings, nativeSync: { ...settings.nativeSync, [key]: value } });
  const updateCustomRule = (index: number, patch: Partial<CustomRule>) => updateRule('customRequiredProperties', settings.rules.customRequiredProperties.map((rule, ruleIndex) => ruleIndex === index ? { ...rule, ...patch } : rule));
  const addCustomRule = () => { if (settings.rules.customRequiredProperties.length >= maxCustomRules) return; const used = new Set(settings.rules.customRequiredProperties.map((rule) => rule.property)); const property = metadata.properties.find((item) => !used.has(item.name)); updateRule('customRequiredProperties', [...settings.rules.customRequiredProperties, { property: property?.name ?? '', label: property?.label ?? 'Required field', weight: 10, severity: 'warning', stageIds: [] }]); };
  const removeCustomRule = (index: number) => updateRule('customRequiredProperties', settings.rules.customRequiredProperties.filter((_, ruleIndex) => ruleIndex !== index));
  const coverage = dashboard.totalDeals > 0 ? Math.round((dashboard.readyDeals / dashboard.totalDeals) * 100) : 0;
  const enabledCoreRules = [settings.rules.requireOwner, settings.rules.requireAmount, settings.rules.requireCloseDate, settings.rules.requireNextStep, settings.rules.requireCompany, settings.rules.requireContact].filter(Boolean).length;
  const healthVariant = dashboard.criticalDeals > 0 ? 'danger' : dashboard.atRiskDeals > 0 ? 'warning' : 'success';

  return <Flex direction="column" gap="large">
    {error && <Alert title="Action required" variant="danger">{error}</Alert>}{notice && <Alert title="Configuration updated" variant="success">{notice}</Alert>}
    <Card><Flex direction="column" gap="medium">
      <Flex direction="row" justify="between" align="center" gap="medium" wrap="wrap"><Flex direction="column" gap="extra-small"><Text variant="microcopy">DEALGUARD CONTROL CENTRE</Text><Heading>Revenue governance & pipeline controls</Heading><Text>Monitor readiness, configure policy, manage reporting outputs and control operational notifications from one workspace.</Text></Flex><Flex direction="row" gap="small" align="center"><StatusTag variant={healthVariant}>{dashboard.criticalDeals > 0 ? 'Action required' : dashboard.atRiskDeals > 0 ? 'Needs attention' : 'Healthy'}</StatusTag><StatusTag variant={plan === 'free' ? 'default' : 'success'}>{planLabel(plan)} plan</StatusTag></Flex></Flex>
      <Divider />
      <Flex direction="row" gap="small" wrap="wrap"><Button onClick={() => void scan()} disabled={working || dashboard.latestScan?.status === 'running'}>{dashboard.latestScan?.status === 'running' ? 'Assessment running…' : 'Run pipeline assessment'}</Button><Button variant="secondary" onClick={() => void load()} disabled={working}>Refresh workspace</Button>{plan === 'free' && <Link href={{ url: 'https://dealguard.rokad.co/pricing', external: true }}>Compare plans</Link>}</Flex>
    </Flex></Card>

    <Flex direction="row" gap="medium" wrap="wrap">
      <Card><Flex direction="column" gap="extra-small"><Text variant="microcopy">READINESS SCORE</Text><Heading>{dashboard.averageScore}/100</Heading><StatusTag variant={dashboard.averageScore >= 80 ? 'success' : dashboard.averageScore >= 60 ? 'warning' : 'danger'}>{dashboard.averageScore >= 80 ? 'Strong' : dashboard.averageScore >= 60 ? 'Watch' : 'At risk'}</StatusTag><Text>Average across {dashboard.totalDeals} assessed deals.</Text></Flex></Card>
      <Card><Flex direction="column" gap="extra-small"><Text variant="microcopy">PIPELINE COVERAGE</Text><Heading>{coverage}%</Heading><Text>{dashboard.readyDeals} ready · {dashboard.atRiskDeals} at risk · {dashboard.criticalDeals} critical</Text><Text variant="microcopy">Readiness distribution across assessed deals.</Text></Flex></Card>
      <Card><Flex direction="column" gap="extra-small"><Text variant="microcopy">GOVERNANCE POLICY</Text><Heading>{enabledCoreRules}/6</Heading><Text>Core information controls enabled</Text><Text variant="microcopy">+ {settings.rules.customRequiredProperties.length} custom rules</Text></Flex></Card>
      <Card><Flex direction="column" gap="extra-small"><Text variant="microcopy">HANDOFF CONTROL</Text><Heading>{dashboard.incompleteHandoffs}</Heading><StatusTag variant={dashboard.incompleteHandoffs > 0 ? 'warning' : 'success'}>{dashboard.incompleteHandoffs > 0 ? 'Open handoffs' : 'Clear'}</StatusTag><Text>Sales-to-delivery handoffs requiring completion.</Text></Flex></Card>
    </Flex>

    <Flex direction="row" gap="medium" wrap="wrap">
      <Card><Flex direction="column" gap="small"><Flex direction="row" justify="between" align="center"><Flex direction="column" gap="extra-small"><Text variant="microcopy">ASSESSMENT STATUS</Text><Text format={{ fontWeight: 'bold' }}>Pipeline monitoring</Text></Flex><StatusTag variant={dashboard.latestScan?.status === 'failed' ? 'danger' : dashboard.latestScan?.status === 'running' ? 'warning' : 'success'}>{dashboard.latestScan?.status ?? 'ready'}</StatusTag></Flex><Text>Last completed: {formatDate(dashboard.lastScanAt)}</Text><Text>Next scheduled: {formatDate(dashboard.nextScanAt)}</Text><Text>{dashboard.latestScan ? `${dashboard.latestScan.scannedCount} deals processed by the latest ${dashboard.latestScan.trigger} assessment.` : 'No assessment history yet.'}</Text></Flex></Card>
      <Card><Flex direction="column" gap="small"><Text variant="microcopy">CONNECTED CAPABILITIES</Text><Flex direction="row" justify="between"><Text>Native reporting</Text><StatusTag variant={nativeStatusVariant(nativeSync.status)}>{nativeSync.status.replace('_', ' ')}</StatusTag></Flex><Flex direction="row" justify="between"><Text>Team notifications</Text><StatusTag variant={slack.connected && slack.status === 'active' ? 'success' : 'default'}>{slack.connected ? slack.status ?? 'connected' : 'not connected'}</StatusTag></Flex><Flex direction="row" justify="between"><Text>Scheduled digest</Text><StatusTag variant={settings.digest.enabled ? 'success' : 'default'}>{settings.digest.enabled ? settings.digest.frequency : 'off'}</StatusTag></Flex></Flex></Card>
    </Flex>

    {(dashboard.topIssues.length > 0 || dashboard.problemDeals.length > 0) && <Card><Flex direction="column" gap="medium"><Flex direction="row" justify="between" align="center"><Flex direction="column" gap="extra-small"><Text variant="microcopy">ATTENTION QUEUE</Text><Heading>Pipeline exceptions</Heading><Text>Prioritised signals from the latest readiness assessment.</Text></Flex><StatusTag variant={dashboard.criticalDeals > 0 ? 'danger' : 'warning'}>{dashboard.problemDeals.length} deals</StatusTag></Flex>{dashboard.topIssues.length > 0 && <Flex direction="row" gap="small" wrap="wrap">{dashboard.topIssues.slice(0, 5).map((issue) => <Card key={issue.code}><Flex direction="column" gap="extra-small"><Text format={{ fontWeight: 'bold' }}>{issue.label}</Text><Heading>{issue.count}</Heading><Text variant="microcopy">affected {issue.count === 1 ? 'deal' : 'deals'}</Text></Flex></Card>)}</Flex>}{dashboard.problemDeals.map((deal) => <Card key={deal.dealId}><Flex direction="column" gap="extra-small"><Flex direction="row" justify="between" align="center"><Text format={{ fontWeight: 'bold' }}>{deal.dealName}</Text><StatusTag variant={statusVariant(deal.status)}>{deal.score}/100 · {deal.status.replace('_', ' ')}</StatusTag></Flex><Text>{deal.pipelineLabel} — {deal.stageLabel}</Text><Text>{deal.readinessSummary}</Text><Text variant="microcopy">Assessed {formatDate(deal.assessedAt)}</Text></Flex></Card>)}</Flex></Card>}

    <Divider /><Flex direction="column" gap="extra-small"><Text variant="microcopy">POLICY & GOVERNANCE</Text><Heading>Readiness policy</Heading><Text>Define what a complete, healthy deal must contain before it progresses through the revenue process.</Text></Flex>
    <Card><Flex direction="column" gap="medium"><Flex direction="row" justify="between" align="center"><Text format={{ fontWeight: 'bold' }}>Activity & stage-age thresholds</Text><StatusTag variant="default">2 controls</StatusTag></Flex><Flex direction="row" gap="medium" wrap="wrap"><NumberInput name="staleDays" label="Inactivity threshold" description="Flag open deals without recent sales activity." value={settings.rules.staleDays} min={1} max={90} onChange={(value) => updateRule('staleDays', Number(value))} /><NumberInput name="maxStageAgeDays" label="Maximum stage age" description="Flag deals remaining in one stage too long." value={settings.rules.maxStageAgeDays} min={1} max={365} onChange={(value) => updateRule('maxStageAgeDays', Number(value))} /></Flex></Flex></Card>
    <Card><Flex direction="column" gap="small"><Flex direction="row" justify="between" align="center"><Text format={{ fontWeight: 'bold' }}>Required deal information</Text><StatusTag variant="success">{enabledCoreRules}/6 enabled</StatusTag></Flex><Text>Apply consistent data-quality requirements to included revenue pipelines.</Text><Toggle label="Deal owner" checked={settings.rules.requireOwner} onChange={(v) => updateRule('requireOwner', v)} /><Toggle label="Deal amount" checked={settings.rules.requireAmount} onChange={(v) => updateRule('requireAmount', v)} /><Toggle label="Close date" checked={settings.rules.requireCloseDate} onChange={(v) => updateRule('requireCloseDate', v)} /><Toggle label="Next step for open deals" checked={settings.rules.requireNextStep} onChange={(v) => updateRule('requireNextStep', v)} /><Toggle label="Associated company" checked={settings.rules.requireCompany} onChange={(v) => updateRule('requireCompany', v)} /><Toggle label="Associated contact" checked={settings.rules.requireContact} onChange={(v) => updateRule('requireContact', v)} /></Flex></Card>
    <Card><Flex direction="column" gap="medium"><Text format={{ fontWeight: 'bold' }}>Scope & exclusions</Text><Text>Exclude administrative pipelines or stages that should not affect revenue-readiness scoring.</Text><MultiSelect name="excludedPipelines" label="Excluded pipelines" options={pipelineOptions} value={settings.rules.excludedPipelineIds} onChange={(v) => updateRule('excludedPipelineIds', v.map(String))} /><MultiSelect name="excludedStages" label="Excluded stages" options={stageOptions} value={settings.rules.excludedStageIds} onChange={(v) => updateRule('excludedStageIds', v.map(String))} /></Flex></Card>

    <Card><Flex direction="column" gap="medium"><Flex direction="row" justify="between" align="center"><Flex direction="column" gap="extra-small"><Text variant="microcopy">ADVANCED POLICY</Text><Heading>Custom property controls</Heading><Text>Require portal-specific deal fields globally or at selected stages.</Text></Flex><StatusTag variant={settings.rules.customRequiredProperties.length >= maxCustomRules ? 'warning' : 'default'}>{settings.rules.customRequiredProperties.length}/{maxCustomRules} rules</StatusTag></Flex>{plan === 'free' && <Alert title="Free plan allowance" variant="info">Your workspace can configure up to 3 custom property controls. Growth supports up to 25.</Alert>}{settings.rules.customRequiredProperties.map((rule, index) => <Card key={`${rule.property}-${index}`}><Flex direction="column" gap="small"><Flex direction="row" justify="between"><Text format={{ fontWeight: 'bold' }}>Policy rule {index + 1}</Text><StatusTag variant={rule.severity === 'critical' ? 'danger' : rule.severity === 'warning' ? 'warning' : 'default'}>{rule.severity}</StatusTag></Flex><Select name={`customProperty${index}`} label="Deal property" options={propertyOptions} value={rule.property} onChange={(value) => { const propertyName = String(value); const property = metadata.properties.find((item) => item.name === propertyName); updateCustomRule(index, { property: propertyName, ...(property ? { label: property.label } : {}) }); }} /><Input name={`customLabel${index}`} label="User-facing label" value={rule.label} onChange={(v) => updateCustomRule(index, { label: v })} /><Flex direction="row" gap="medium" wrap="wrap"><Select name={`customSeverity${index}`} label="Severity" options={[{ label: 'Information', value: 'info' }, { label: 'Warning', value: 'warning' }, { label: 'Critical', value: 'critical' }]} value={rule.severity} onChange={(v) => updateCustomRule(index, { severity: String(v) as Severity })} /><NumberInput name={`customWeight${index}`} label="Score deduction" value={rule.weight} min={1} max={30} onChange={(v) => updateCustomRule(index, { weight: Number(v) })} /></Flex><MultiSelect name={`customStages${index}`} label="Stage scope" description="Leave empty to apply in every included stage." options={stageOptions} value={rule.stageIds} onChange={(v) => updateCustomRule(index, { stageIds: v.map(String) })} /><Button variant="secondary" onClick={() => removeCustomRule(index)} disabled={working}>Remove rule</Button></Flex></Card>)}<Button variant="secondary" onClick={addCustomRule} disabled={working || settings.rules.customRequiredProperties.length >= maxCustomRules}>Add policy rule</Button></Flex></Card>

    <Divider /><Flex direction="column" gap="extra-small"><Text variant="microcopy">OPERATIONS & AUTOMATION</Text><Heading>Reporting and integrations</Heading><Text>Control where DealGuard outputs appear and how operational teams are notified.</Text></Flex>
    <Flex direction="row" gap="medium" wrap="wrap"><Card><Flex direction="column" gap="small"><Flex direction="row" justify="between"><Text format={{ fontWeight: 'bold' }}>Native reporting</Text><StatusTag variant={nativeStatusVariant(nativeSync.status)}>{nativeSync.status.replace('_', ' ')}</StatusTag></Flex><Text>Publish score, status, grade, issue count, handoff state and assessment context into namespaced deal properties.</Text>{!nativeSync.entitled && <Alert title="Growth capability" variant="info">Upgrade to enable native reporting fields and workflow-ready outputs.</Alert>}{nativeSync.lastError && <Alert title="Reporting issue" variant="danger">{nativeSync.lastError}</Alert>}<Toggle label="Sync assessment results to deal properties" checked={settings.nativeSync.enabled} onChange={(v) => updateNative('enabled', v)} /><Toggle label="Include readable readiness summary" checked={settings.nativeSync.includeSummary} onChange={(v) => updateNative('includeSummary', v)} /><Flex direction="row" gap="small" wrap="wrap"><Button variant="secondary" onClick={() => void provisionNative()} disabled={working || !nativeSync.entitled || nativeSync.status === 'provisioning' || nativeSync.status === 'backfilling'}>{nativeSync.status === 'ready' ? 'Verify fields' : 'Provision fields'}</Button><Button variant="secondary" onClick={() => void backfillNative()} disabled={working || !nativeSync.entitled || nativeSync.status !== 'ready' || !settings.nativeSync.enabled}>Backfill history</Button></Flex><Text variant="microcopy">Schema v{nativeSync.propertyVersion || '—'} · Last backfill {formatDate(nativeSync.lastBackfillAt)}{nativeSync.lastBackfillAt ? ` · ${nativeSync.lastBackfillCount} deals` : ''}</Text></Flex></Card>
    <Card><Flex direction="column" gap="small"><Flex direction="row" justify="between"><Text format={{ fontWeight: 'bold' }}>Team notifications</Text><StatusTag variant={slack.connected && slack.status === 'active' ? 'success' : 'default'}>{slack.connected ? slack.status ?? 'connected' : 'not connected'}</StatusTag></Flex>{!slack.entitled && <Alert title="Growth capability" variant="info">Upgrade to enable team alerts and workflow notifications.</Alert>}{slack.connected ? <><Text>{slack.teamName} · {slack.channelName}</Text><Toggle label="Enable notifications" checked={settings.notifications.slack.enabled} onChange={(v) => updateSlack('enabled', v)} /><Toggle label="Critical deal alerts" checked={settings.notifications.slack.alertOnCritical} onChange={(v) => updateSlack('alertOnCritical', v)} /><Toggle label="Handoff required alerts" checked={settings.notifications.slack.alertOnHandoffRequired} onChange={(v) => updateSlack('alertOnHandoffRequired', v)} /><Toggle label="Handoff confirmed alerts" checked={settings.notifications.slack.alertOnHandoffConfirmed} onChange={(v) => updateSlack('alertOnHandoffConfirmed', v)} /><NumberInput name="slackCooldown" label="Repeat-alert cooldown (minutes)" value={settings.notifications.slack.cooldownMinutes} min={15} max={1440} onChange={(v) => updateSlack('cooldownMinutes', Number(v))} /><Flex direction="row" gap="small"><Button variant="secondary" onClick={() => void testSlack()} disabled={working}>Send test</Button><Button variant="secondary" onClick={() => void disconnectSlack()} disabled={working}>Disconnect</Button></Flex></> : <><Text>Connect a team workspace to route governed pipeline alerts to the people responsible for action.</Text><Button variant="secondary" onClick={() => void prepareSlackConnection()} disabled={working || !slack.entitled}>Connect workspace</Button>{slackAuthorizeUrl && <Link href={{ url: slackAuthorizeUrl, external: true }}>Open secure authorisation</Link>}</>}</Flex></Card></Flex>

    <Card><Flex direction="column" gap="medium"><Flex direction="row" justify="between"><Flex direction="column" gap="extra-small"><Text variant="microcopy">EXECUTIVE REPORTING</Text><Heading>Pipeline digest</Heading><Text>Deliver a scheduled summary of pipeline health and readiness exceptions.</Text></Flex><StatusTag variant={settings.digest.enabled ? 'success' : 'default'}>{settings.digest.enabled ? 'Active' : 'Off'}</StatusTag></Flex><Toggle label="Enable scheduled digest" checked={settings.digest.enabled} onChange={(v) => updateDigest('enabled', v)} /><Input name="digestRecipients" label="Recipients" description="Comma-separated email addresses." value={recipients} onChange={setRecipients} /><Flex direction="row" gap="medium" wrap="wrap"><Select name="digestFrequency" label="Frequency" value={settings.digest.frequency} options={plan === 'free' ? [{ label: 'Weekly', value: 'weekly' }] : [{ label: 'Daily', value: 'daily' }, { label: 'Weekly', value: 'weekly' }]} onChange={(v) => updateDigest('frequency', String(v) as Settings['digest']['frequency'])} />{settings.digest.frequency === 'weekly' && <Select name="digestDay" label="Delivery day" value={settings.digest.dayOfWeek} options={[{ label: 'Sunday', value: 0 }, { label: 'Monday', value: 1 }, { label: 'Tuesday', value: 2 }, { label: 'Wednesday', value: 3 }, { label: 'Thursday', value: 4 }, { label: 'Friday', value: 5 }, { label: 'Saturday', value: 6 }]} onChange={(v) => updateDigest('dayOfWeek', Number(v))} />}<NumberInput name="digestHour" label="Delivery hour (UTC)" value={settings.digest.hourUtc} min={0} max={23} onChange={(v) => updateDigest('hourUtc', Number(v))} /></Flex><Button variant="secondary" onClick={() => void testDigest()} disabled={working || !settings.digest.enabled}>Send test digest</Button></Flex></Card>

    <Card><Flex direction="column" gap="medium"><Flex direction="row" justify="between" align="center"><Flex direction="column" gap="extra-small"><Text variant="microcopy">SUBSCRIPTION</Text><Heading>{planLabel(plan)} plan</Heading><Text>{plan === 'free' ? 'Core pipeline readiness with essential governance controls.' : 'Advanced governance, reporting, integrations and higher policy limits.'}</Text></Flex><StatusTag variant={plan === 'free' ? 'default' : 'success'}>{plan === 'free' ? 'Current plan' : 'Active'}</StatusTag></Flex>{plan === 'free' && <><Divider /><Flex direction="row" gap="medium" wrap="wrap"><Card><Flex direction="column" gap="extra-small"><Text format={{ fontWeight: 'bold' }}>Free</Text><Text>Weekly digest</Text><Text>Up to 3 custom rules</Text><Text>Core readiness controls</Text><StatusTag variant="default">Current</StatusTag></Flex></Card><Card><Flex direction="column" gap="extra-small"><Text format={{ fontWeight: 'bold' }}>Growth</Text><Text>Daily or weekly digest</Text><Text>Up to 25 custom rules</Text><Text>Native reporting & team notifications</Text><StatusTag variant="success">Recommended</StatusTag></Flex></Card></Flex><Link href={{ url: 'https://dealguard.rokad.co/pricing', external: true }}>View upgrade options</Link></>}</Flex></Card>

    <Card><Flex direction="row" justify="between" align="center" gap="medium" wrap="wrap"><Flex direction="column" gap="extra-small"><Text format={{ fontWeight: 'bold' }}>Save governance configuration</Text><Text>Changes affect future assessments, reporting outputs, digests and notifications.</Text></Flex><Flex direction="row" gap="small"><Button variant="secondary" onClick={() => void load()} disabled={working}>Discard changes</Button><Button variant="primary" onClick={() => void save()} disabled={working}>{working ? 'Working…' : 'Save configuration'}</Button></Flex></Flex></Card>
  </Flex>;
};
